### ISSUE TITLE
Deployment status needs to give users more info

### ISSUE THREAD

**Issue by pcm32** [phnmnl/ng2-phenomenal-portal#2]
The deployment progress bar should probably be accompanied by a list of steps that are completed sequentially, with some rough time estimate for each, including an overall time estimate. This data could be drawn from the logs file that the tsi portal can inspect (which I presume must be available through some API call).

We should also display a deployment ID that is not very notorious, but that would make it into any screenshot that the user uses for reporting a problem. This will allow us to map error reports with the files made available on the slack channel for deployment errors.

**Comment by pcm32** [comment]
@steinbeck said:
"My request for more granular reporting of launch events and proper tagging of deployments with date and time on our portal and the TSI portal still stands."

**Comment by kikkomep** [comment]
I think that this issue is now fixed. @pcm32 What do you think?

**Comment by sneumann** [comment]
I just deployed and I find great lot of feedback. Well done! 
Please re-open if I am wrong. Yours, Steffen
