### ISSUE TITLE
Deployment: initially logfile button/link undefined

### ISSUE THREAD

**Issue by sneumann** [phnmnl/ng2-phenomenal-portal#28]
Hi, 
for a fresh deployment, log file button points to 
https://portaldev.phenomenal-h2020.eu/logs?id=undefined
and only after the instances are up changes to 
https://portaldev.phenomenal-h2020.eu/logs?id=TSI15.......87

-> Button should be disabled / `Waiting for logfiles` or the 
`id=undefined`page should have static content "will be available in a few minutes".

Yours, Steffen

**Comment by kikkomep** [comment]
Fixed by 112f1532d7e72aaea54be5a6ec87995fd056e3aa
