### ISSUE TITLE
Enhancement: Follow logfiles / scroll to end

### ISSUE THREAD

**Issue by sneumann** [phnmnl/ng2-phenomenal-portal#29]
Hi, it is not very convenient to follow a deployment logfile.
It would be great to have an "scroll-to-end" button/arrow,
and/or have a "scroll/follow end of log" button, like on travis:
https://travis-ci.org/sneumann/mzR/
Yours, Steffen

**Comment by kikkomep** [comment]
Feature implemented in https://github.com/phnmnl/ng2-phenomenal-portal/pull/46
