### ISSUE TITLE
FAQ shouldn't be hardcoded in ng2 project

### ISSUE THREAD

**Issue by pcm32** [phnmnl/ng2-phenomenal-portal#3]
The content available at https://portal.phenomenal-h2020.eu/help/faq is currently hard coded [here](https://github.com/phnmnl/ng2-phenomenal-portal/blob/f632e07426d136f5fb914119b35efd6ea331b358/documentation/components/FaqComponent.html#L916) apparently. The FAQ should be populated very much in the same way that the wiki and app library pages are, which depend on content populated and independently updated from the phenomenal git repos.

**Comment by pcm32** [comment]
ping @ilveroluca @kikkomep. @namratakale is preparing the markdown page for the FAQ, but we would need some help from CRS4 to take care of the angular side, do you think this is feasible? Thanks!

**Comment by kikkomep** [comment]
Yes @pcm32! It should be relatively simple to dynamically populate the FAQ section in the same way that the Wiki and AppLibrary pages are.

**Comment by namratakale** [comment]
I have started a markdown page for FAQ https://github.com/phnmnl/phenomenal-h2020/wiki/FAQs

**Comment by kikkomep** [comment]
Addressed by the pull requests https://github.com/phnmnl/ng2-phenomenal-portal/pull/54 and  https://github.com/phnmnl/php-phenomenal-portal-wiki/pull/3
