### ISSUE TITLE
Galaxy admin credentials not set

### ISSUE THREAD

**Issue by sneumann** [phnmnl/ng2-phenomenal-portal#30]
Hi, I just created an instance from portaldev on Amazon (TSI1519243606387). 
After the deployment, my https://portaldev.phenomenal-h2020.eu/cloud-research-environment-dashboard
showed the admin eMail and Password-Key-Button. I could not log into Galaxy 
with these credentials. I could add (register) a new user in Galaxy 
with `sneumann(at)ipb-halle.de` which otherwise I would expect to collide
with the automated one. Yours, Steffen

**Comment by kikkomep** [comment]
Fixed by **Cerebellin** release of cloud-deploy-kubenow
