### ISSUE TITLE
Cache invalidation issue

### ISSUE THREAD

**Issue by ilveroluca** [phnmnl/ng2-phenomenal-portal#43]
The portal has a problem with caching on the user side.  When code updates are deployed, the update isn't downloaded by the client (they need to clear their cache to trigger a download).  This might also be related to the problems we've see with images not being loaded -- it looks like the server is returning HTTP 304 in those cases (`NOT MODIFIED`).

**Comment by ilveroluca** [comment]
@andersla suggests using a "random string on the essential `pages?random=kjhfsiuy79yr4h3kuj4hrk`" as a possible quick solution.  However, I guess this would case the portal code to be downloaded at every visit to the portal, even when the code hasn't been updated.

**Comment by kikkomep** [comment]
Partially addressed by the following two pull requests:
* https://github.com/phnmnl/ng2-phenomenal-portal/pull/45;
* https://github.com/phnmnl/container-phenomenal-portal/pull/9.

They enable a better versioning of the software distribution and allow the browser to load the right version of the deployed software .

**Comment by kikkomep** [comment]
The issue with AppLibrary images not being loaded has been fixed via https://github.com/phnmnl/php-phenomenal-portal-app-library/pull/3 and https://github.com/phnmnl/container-phenomenal-portal-app-library/pull/1

**Comment by kikkomep** [comment]
Same issue with Wiki images has been fixed through https://github.com/phnmnl/php-phenomenal-portal-wiki/pull/2 and https://github.com/phnmnl/container-phenomenal-portal-wiki/pull/2
