### ISSUE TITLE
Make CRE list more informative when it's empty

### ISSUE THREAD

**Issue by ilveroluca** [phnmnl/ng2-phenomenal-portal#67]
The CRE list isn't very informative when it's empty.  People who don't understand what the "+" means right away might feel lost.

I suggest:
1. change the page title/header to "Your Cloud Research Environments";
2. consider, when the list is empty, placing a note that tells the user to "click on the '+' to create a new CRE"

![empty_cre_screen](https://user-images.githubusercontent.com/1502936/40738440-de0d1ad6-6443-11e8-8ffb-1ab8e2652588.png)

**Comment by michaelvanvliet** [comment]
Very good improvement! Would it be possible to write "...create a new research environment", instead of using the acronym CRE?

**Comment by kikkomep** [comment]
Addressed by #78 
![medium-large](https://user-images.githubusercontent.com/1832243/42581574-5d2f3092-852d-11e8-9177-9435de295c1a.png)
