### ISSUE TITLE
Empty flavours in Giessen (again)

### ISSUE THREAD

**Issue by sneumann** [phnmnl/ng2-phenomenal-portal#69]
Hi, it seems the issue #21 has resurfaced. The portaldev can successfully authenticate,
but flavours / networks are empty. Tested on firefox and chrome.
Console shows 
`Failed to load resource: the server responded with a status of 401 (https://api.portal.tsi.ebi.ac.uk/application/)`

I tried both my existing and working RC file, and a fresh openstackrc, 
but manually comparing the file and also the `OS_*` variable shows no differences between the two. 
The OpenStack in Giessen has recently been upgraded to the queens release.
A deployment to Bielefeld worked directly afterwards.

Yours, Steffen

**Comment by sneumann** [comment]
So the curl we had in `test.sh` mentioned in #21 indeed gives an empty list, 
but no error message. 
`curl https://api.portal.tsi.ebi.ac.uk/cloudprovidermetadata/flavors -H Origin: https://portaldev.phenomenal-h2020.eu -H Accept-Encoding: gzip, deflate, br -H Accept-Language: en-US,en;q=0.9,fr;q=0.8,it;q=0.7 -H Authorization: Bearer eyJhbGc...uODSQ -H Content-Type: application/json -H Accept: application/json -H Referer: https://portaldev.phenomenal-h2020.eu/cloud-research-environment-setup -H User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36 -H Connection: keep-alive --data-binary "{\"username\": \"sneumann\", \"password\": \"XXX\", \"tenantName\": \"phenomenal\", \"domainName\": \"de.NBI\", \"endpoint\": \"https://cloud.computational.bio.uni-giessen.de:5000/v3\", \"version\": \"3\"}"`

**Comment by sneumann** [comment]
Hi, turns out that I have the same issue in Bielefeld, so it's not an isolated problem with one particular instance. Yours, Steffen

**Comment by kikkomep** [comment]
@sneumann Can you check with the version 3.0.0-rc1 deployed on https://portaldev.phenomenal-h2020.eu/ ?

**Comment by kikkomep** [comment]
Great! We have a new backend to query flavours, networks, etc..., totally independent of the TSI. 
You can find [here](https://github.com/phnmnl/portal-metadata-backend/commit/d2be83afc2b63cd72baf029130ab655c7c65420e) the service related with OpenStack.
