### ISSUE TITLE
Warn user when closing tab before deployment request is fully transmitted

### ISSUE THREAD

**Issue by ilveroluca** [phnmnl/ng2-phenomenal-portal#70]
When creating a new deployment there's a time window between when the user clicks the "Deploy" button and when the deployment action has been successfully transmitted to the TSI portal, during which closing the tab will cause the user to lose the deployment attempt.

A workable solution would be to have the browser popup a confirmation prompt if the user tries to close the tab before it's safe to do so.

**Comment by kikkomep** [comment]
Fixed by #71
